### ISSUE TITLE
Problems with polybar 

### ISSUE THREAD

**Issue by LucaErr** [vaxerski/Hypr#37] opened 2022-03-08 17:59 UTC
**Please describe the bug**
1)Polybar ewmh module disappear when i try to use a second monitor, and when it appear it isn't even clickable.
2) When i start my polybar sometimes the modules are placed randomly (if 

**Steps to reproduce:**
These are my config file:
1) [ewmh.ini](https://pastebin.com/uc319ubF) xworkspaces module
2) [config](https://pastebin.com/EPCe4zKt) the general polybar config
3) [center.ini ](https://pastebin.com/SK0JR6ia) my center config bar
4) [hypr.conf](https://pastebin.com/EZQMPyvi)

**Expected behavior**
obviously i expected to see the module/s working normally

**Screenshots**
here's some videos

https://user-images.githubusercontent.com/73197383/157289199-ad53f17d-a772-42b1-ace5-22bad28ef943.mov

https://user-images.githubusercontent.com/73197383/157296891-a496a929-671f-4335-a25c-de91057b7ac2.mov

**Log:**

 [hypr.log](https://github.com/vaxerski/Hypr/files/8208254/hypr.log)

_can't upload a normal pastebin so i posted all the log file cuz when i try to edit the file my pc literally blows out, there are more than 10000 lines, and my lil i5 5300u can't manage to open it :(_ 

***IF MORE INFORMATION ARE NEEDED PLEASE CONTACT ME***

**Comment by vaxerski** [comment] 2022-03-08 19:17
fixed ordering.

By default, all workspaces are defined on the first display, because Hypr does not support assigning workspaces to displays. Therefore, a temporary fix would be to make

`pin-workspaces = false`

I will issue a patch for that soon.

Regarding clicking, yeah it doesnt work and i am pretty sure I know why, I'll test a bit.

**Comment by vaxerski** [comment] 2022-03-08 19:27
`pin-workspaces` should now work after 296096596bb4943337367eb0b97b309f694d463d

clicking not yet.

**Comment by LucaErr** [comment] 2022-03-08 20:11
nothing, when i switch into an empty workspace still disappear

**Comment by vaxerski** [comment] 2022-03-08 20:12
what disappears??

I used your config and it works as expected:
![image](https://user-images.githubusercontent.com/43317083/157317197-86a8ea3d-8692-4442-82b9-e165703af3cc.png)

**Comment by LucaErr** [comment] 2022-03-08 20:31
uhmm, is there a way to completely uninstall hypr and reinstall it ? Cuz it still start my modules randomly and disappearing when i try to switch workspace.

**Comment by vaxerski** [comment] 2022-03-08 20:35
the only thing hypr uses as an executable is the one located in /bin/ if you installed manually or in (somewhere else) if you installed with the AUR. You should only replace it with the new version. (or do a `yay -S hypr-git` or whichever AUR helper you use in the case of AUR)

Please describe what's happening in more depth. What modules are you talking about, the Hypr bar's or the Polybar's ones?

**Comment by LucaErr** [comment] 2022-03-08 21:01
now i removed it from exec but still no changes here a more specific video of the problems that i am encountering.

https://user-images.githubusercontent.com/73197383/157324144-eeb33219-66e8-46c0-ba6d-05eb77d33ca4.mov

**Comment by vaxerski** [comment] 2022-03-08 21:08
okay I can see that.

regarding the positions: I will look into this in a sec, thanks.

regarding the xworkspaces: they do not disappear for me. Please send either your entire config or show that it happens with the config you provided me.

In the meantime, the support for click-to-switch workspaces has been added in ea670a4b94b515d319e2e9938fb9b92e7f0fdb34

**Comment by vaxerski** [comment] 2022-03-08 21:14
dock positioning (the module clumping) should be fixed in 8d499c62ab4a599403880072e33e215b5e8c6fbd

**Comment by LucaErr** [comment] 2022-03-08 21:31
https://github.com/vaxerski/Hypr/commit/8d499c62ab4a599403880072e33e215b5e8c6fbd SOLVED MODULE CLUMPING ✔️

**Comment by vaxerski** [comment] 2022-03-08 21:46
I can't reproduce the bar disappearing.

What you can do is:
launch your polybar with the xworkspaces module from the terminal and look for any errors
(`polybar center -c "/path/to/config"`)
as soon as the polybar module dies, if polybar doesnt report any abnormalities, copy the hypr log from /tmp/hypr/hypr.log and attach it here for me to analyze.

**Comment by LucaErr** [comment] 2022-03-08 21:52
i  think it is a  polybar problem 
```
arch ~ » polybar center -c ~/.config/polybar/config       130 ↵
notice: Parsing config file: /home/luca/.config/polybar/config
notice: Loaded font "ProductSans:size=10" (name=Product Sans, offset=1, file=/home/luca/.local/share/fonts/FontsFree-Net-ProductSans-Bold.ttf)
notice: Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Unifont, offset=0, file=/usr/share/fonts/Unifont/Unifont.ttf)
notice: Loaded font "siji:pixelsize=10" (name=siji, offset=1, file=/usr/share/fonts/misc/siji.ttf)
notice: Loaded font "FontAwesome6Free:style=Solid:size=10" (name=Font Awesome 6 Free, offset=2, file=/usr/share/fonts/OTF/Font Awesome 6 Free-Solid-900.otf)
notice: Loaded font "FontAwesome6Free:style=Regular:size=10" (name=Font Awesome 6 Free, offset=2, file=/usr/share/fonts/OTF/Font Awesome 6 Free-Regular-400.otf)
notice: Loaded font "FontAwesome6Brands:style=Regular:size=10" (name=Font Awesome 6 Brands, offset=2, file=/usr/share/fonts/OTF/Font Awesome 6 Brands-Regular-400.otf)
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; std::vector<_Tp, _Alloc>::reference = std::__cxx11::basic_string<char>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    8930 IOT instruction (core dumped)  polybar center -c ~/.config/polybar/config
arch ~ » polybar center -c ~/.config/polybar/config       134 ↵
notice: Parsing config file: /home/luca/.config/polybar/config
notice: Loaded font "ProductSans:size=10" (name=Product Sans, offset=1, file=/home/luca/.local/share/fonts/FontsFree-Net-ProductSans-Bold.ttf)
notice: Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Unifont, offset=0, file=/usr/share/fonts/Unifont/Unifont.ttf)
notice: Loaded font "siji:pixelsize=10" (name=siji, offset=1, file=/usr/share/fonts/misc/siji.ttf)
notice: Loaded font "FontAwesome6Free:style=Solid:size=10" (name=Font Awesome 6 Free, offset=2, file=/usr/share/fonts/OTF/Font Awesome 6 Free-Solid-900.otf)
notice: Loaded font "FontAwesome6Free:style=Regular:size=10" (name=Font Awesome 6 Free, offset=2, file=/usr/share/fonts/OTF/Font Awesome 6 Free-Regular-400.otf)
notice: Loaded font "FontAwesome6Brands:style=Regular:size=10" (name=Font Awesome 6 Brands, offset=2, file=/usr/share/fonts/OTF/Font Awesome 6 Brands-Regular-400.otf)
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; std::vector<_Tp, _Alloc>::reference = std::__cxx11::basic_string<char>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    8970 IOT instruction (core dumped)  polybar center -c ~/.config/polybar/config
```

**Comment by vaxerski** [comment] 2022-03-08 21:54
Try with `polybar-git` from the AUR (that's what I am using) as I remember having this same issue some time ago with the standalone release.

**Comment by LucaErr** [comment] 2022-03-08 22:10
Perfect, now everything work as expected. Tysm !

**Comment by vaxerski** [comment] 2022-03-08 22:11
Glad to hear! Closing then =)

**Closed** 2022-03-08 22:11 UTC
Labels: bug

**Comment by mk1923** [comment] 2022-04-04 09:28
I'm having the same issue of the bar disappearing when switching to an empty workspace. Since switching to the Git version seems to have solved it for you, I'm curious whether the problem lies in missing dependencies for the module which are only required when compiling, or if it is caused by something a commit had fixed which has not yet made it to release? 

Void does not ship Git packages and since I'd like to keep xbps updates I'd rather just wait if the case was indeed something fixed with a commit, rather than something else.
